version: '3.0'

services:
  service-discovery:
    build:
      context: ./service-discovery
    container_name: service-discovery
    ports:
     - "8080:8080"
    volumes:
     - ./service-discovery:/app
     - ~/.m2:/root/.m2
    networks:
     - app-network

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
     - "8081:8081" # Porta definida no application.properties
    volumes:
     - ./product-service:/app
     - ~/.m2:/root/.m2
    depends_on:
     - service-discovery
    networks:
     - app-network

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
     - "8082:8082" # Porta definida no application.properties
    volumes:
     - ./order-service:/app
     - ~/.m2:/root/.m2
    depends_on:
     - service-discovery
    networks:
     - app-network

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
     - "8084:8080"
    volumes:
     - ./auth-service:/app
     - ~/.m2:/root/.m2
    depends_on:
     - service-discovery
    networks:
     - app-network
  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
     - "8083:8080"
    volumes:
     - ./gateway-service:/app
     - ~/.m2:/root/.m2
    depends_on:
     - service-discovery
     - product-service
     - order-service
    networks:
     - app-network
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
     - "80:80"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
     - gateway-service
    networks:
     - app-network
networks:
  app-network:
    driver: bridge
